-- Índices não criados implicitamente por PRIMARY KEY/UNIQUE.
-- Fonte: Supabase Management API em 2026-07-28.

set search_path = pg_catalog, public, extensions;

CREATE INDEX idx_adicionais_categoria ON adicionais USING btree (categoria);
CREATE INDEX idx_adicionais_disponivel ON adicionais USING btree (disponivel);
CREATE INDEX idx_anotacoes_painel_categoria ON anotacoes_painel USING btree (categoria);
CREATE INDEX idx_anotacoes_painel_concluida ON anotacoes_painel USING btree (concluida);
CREATE INDEX idx_anotacoes_painel_created_at ON anotacoes_painel USING btree (created_at DESC);
CREATE INDEX idx_anotacoes_painel_prioridade ON anotacoes_painel USING btree (prioridade);
CREATE INDEX idx_atividade_garcom_created_at ON atividade_garcom USING btree (created_at DESC);
CREATE INDEX idx_atividade_garcom_garcom_id ON atividade_garcom USING btree (garcom_id);
CREATE INDEX idx_atividade_garcom_item_pedido_id ON atividade_garcom USING btree (item_pedido_id);
CREATE INDEX idx_atividade_garcom_pedido_id ON atividade_garcom USING btree (pedido_id) WHERE pedido_id IS NOT NULL;
CREATE INDEX idx_atividade_garcom_tipo ON atividade_garcom USING btree (tipo_acao);
CREATE INDEX idx_bebidas_categoria ON bebidas USING btree (categoria);
CREATE INDEX idx_bebidas_disponivel ON bebidas USING btree (disponivel);
CREATE INDEX idx_caixas_data ON caixas USING btree (data_abertura);
CREATE INDEX idx_caixas_status ON caixas USING btree (status);
CREATE UNIQUE INDEX idx_caixas_um_aberto ON caixas USING btree (status) WHERE status::text = 'aberto'::text;
CREATE INDEX idx_categorias_adicionais_nome ON categorias_adicionais USING btree (nome);
CREATE INDEX idx_categorias_cardapio_ativo_ordem ON categorias_cardapio USING btree (ativo, ordem, nome);
CREATE INDEX idx_combo_itens_bebida_id ON combo_itens USING btree (bebida_id);
CREATE INDEX idx_combo_itens_combo_id ON combo_itens USING btree (combo_id);
CREATE INDEX idx_combo_itens_produto_id ON combo_itens USING btree (produto_id);
CREATE INDEX idx_configuracoes_loja_chave ON configuracoes_loja USING btree (chave);
CREATE INDEX idx_crediario_contas_cliente_id ON crediario_contas USING btree (cliente_id) WHERE cliente_id IS NOT NULL;
CREATE INDEX idx_crediario_contas_cliente_nome ON crediario_contas USING gin (to_tsvector('portuguese'::regconfig, cliente_nome));
CREATE INDEX idx_crediario_contas_status_saldo ON crediario_contas USING btree (status, saldo_atual DESC, atualizado_em DESC);
CREATE INDEX idx_crediario_movimentos_conta_data ON crediario_movimentos USING btree (conta_id, realizado_em DESC);
CREATE INDEX idx_crediario_movimentos_pedido ON crediario_movimentos USING btree (pedido_id) WHERE pedido_id IS NOT NULL;
CREATE UNIQUE INDEX idx_crediario_movimentos_pedido_consumo ON crediario_movimentos USING btree (pedido_id) WHERE pedido_id IS NOT NULL AND tipo = 'consumo'::text AND origem = 'pedido'::text;
CREATE INDEX idx_cupons_aplica_em ON cupons USING btree (aplica_em);
CREATE INDEX idx_cupons_ativo ON cupons USING btree (ativo);
CREATE UNIQUE INDEX idx_cupons_codigo_unico ON cupons USING btree (codigo);
CREATE INDEX idx_cupons_combo_id ON cupons USING btree (combo_id);
CREATE INDEX idx_cupons_produto_id ON cupons USING btree (produto_id);
CREATE INDEX idx_cupons_validade_fim ON cupons USING btree (validade_fim);
CREATE INDEX idx_cupons_usos_created_at ON cupons_usos USING btree (created_at DESC);
CREATE INDEX idx_cupons_usos_cupom_id ON cupons_usos USING btree (cupom_id);
CREATE INDEX idx_cupons_usos_telefone ON cupons_usos USING btree (telefone_cliente);
CREATE INDEX idx_entregas_created_at_id ON entregas USING btree (created_at DESC, id DESC);
CREATE INDEX idx_entregas_entregador_id ON entregas USING btree (entregador_id);
CREATE INDEX idx_entregas_excluida_repasse ON entregas USING btree (excluida_repasse) WHERE excluida_repasse = true;
CREATE INDEX idx_entregas_pedido_id ON entregas USING btree (pedido_id);
CREATE INDEX idx_entregas_status ON entregas USING btree (status);
CREATE INDEX idx_entregas_status_created_at_id ON entregas USING btree (status, created_at DESC, id DESC);
CREATE INDEX idx_fila_impressao_automaticos_pendentes ON fila_impressao USING btree (criado_em) WHERE status::text = 'pendente'::text AND automatico = true;
CREATE INDEX idx_fila_impressao_criado_em ON fila_impressao USING btree (criado_em);
CREATE INDEX idx_fila_impressao_pedido_tipo_status ON fila_impressao USING btree (pedido_id, tipo, status);
CREATE INDEX idx_fila_impressao_pendentes_criado_em ON fila_impressao USING btree (criado_em) WHERE status::text = 'pendente'::text;
CREATE INDEX idx_fila_impressao_status ON fila_impressao USING btree (status);
CREATE INDEX idx_fila_impressao_status_criado_em ON fila_impressao USING btree (status, criado_em);
CREATE UNIQUE INDEX uq_fila_impressao_hash_ativo ON fila_impressao USING btree (hash_evento) WHERE hash_evento IS NOT NULL AND (status::text = ANY (ARRAY['pendente'::character varying, 'processando'::character varying]::text[]));
CREATE INDEX financas_diarias_data_referencia_idx ON financas_diarias USING btree (data_referencia);
CREATE INDEX financas_diarias_funcionario_id_idx ON financas_diarias USING btree (funcionario_id) WHERE funcionario_id IS NOT NULL;
CREATE INDEX financas_diarias_movimentacao_id_idx ON financas_diarias USING btree (movimentacao_id);
CREATE INDEX idx_formas_pagamento_ativo_visivel_ordem ON formas_pagamento USING btree (ativo, visivel_cliente, ordem);
CREATE INDEX idx_formas_pagamento_ordem ON formas_pagamento USING btree (ordem, nome);
CREATE INDEX idx_historico_caixas_ano ON historico_caixas USING btree (ano);
CREATE INDEX idx_historico_entregas_ano ON historico_entregas USING btree (ano);
CREATE INDEX idx_historico_entregas_historico_pedido_id ON historico_entregas USING btree (historico_pedido_id);
CREATE INDEX idx_historico_item_adicionais_historico_item_id ON historico_item_adicionais USING btree (historico_item_id);
CREATE INDEX idx_historico_itens_ano ON historico_itens_pedido USING btree (ano);
CREATE INDEX idx_historico_itens_pedido_historico_pedido_id ON historico_itens_pedido USING btree (historico_pedido_id);
CREATE INDEX idx_historico_movimentacoes_ano ON historico_movimentacoes_caixa USING btree (ano);
CREATE INDEX idx_historico_pedidos_ano ON historico_pedidos USING btree (ano);
CREATE INDEX idx_item_adicionais_adicional_id ON item_adicionais USING btree (adicional_id);
CREATE INDEX idx_item_adicionais_item_pedido_id ON item_adicionais USING btree (item_pedido_id);
CREATE INDEX idx_itens_pedido_bebida_id ON itens_pedido USING btree (bebida_id);
CREATE INDEX idx_itens_pedido_combo_id ON itens_pedido USING btree (combo_id);
CREATE INDEX idx_itens_pedido_garcom_id ON itens_pedido USING btree (adicionado_por_garcom_id) WHERE adicionado_por_garcom_id IS NOT NULL;
CREATE INDEX idx_itens_pedido_pedido_id ON itens_pedido USING btree (pedido_id);
CREATE INDEX idx_itens_pedido_produto_id ON itens_pedido USING btree (produto_id);
CREATE UNIQUE INDEX idx_mesas_codigo_qr_unique ON mesas USING btree (codigo_qr);
CREATE INDEX idx_mesas_numero ON mesas USING btree (numero);
CREATE INDEX idx_mesas_pedido_id ON mesas USING btree (pedido_id);
CREATE INDEX idx_mesas_status ON mesas USING btree (status);
CREATE UNIQUE INDEX idx_mesas_tipo_numero_unique ON mesas USING btree (tipo, numero);
CREATE INDEX idx_mesas_tipo_status ON mesas USING btree (tipo, status);
CREATE INDEX idx_mesas_tipo_status_pedido ON mesas USING btree (tipo, status, pedido_id);
CREATE INDEX idx_movimentacoes_caixa_caixa_created ON movimentacoes_caixa USING btree (caixa_id, created_at DESC);
CREATE INDEX idx_movimentacoes_caixa_caixa_id ON movimentacoes_caixa USING btree (caixa_id);
CREATE INDEX idx_movimentacoes_caixa_categoria_id ON movimentacoes_caixa USING btree (categoria_id);
CREATE INDEX idx_movimentacoes_caixa_funcionario_id ON movimentacoes_caixa USING btree (funcionario_id);
CREATE UNIQUE INDEX idx_movimentacoes_caixa_pedido_unico ON movimentacoes_caixa USING btree (pedido_id);
CREATE INDEX idx_movimentacoes_caixa_tipo ON movimentacoes_caixa USING btree (tipo);
CREATE INDEX idx_notification_preferences_user_id ON notification_preferences USING btree (user_id);
CREATE INDEX idx_pagamentos_entregadores_data ON pagamentos_entregadores USING btree (data_referencia DESC);
CREATE INDEX idx_pagamentos_entregadores_data_id ON pagamentos_entregadores USING btree (data_referencia DESC, id DESC);
CREATE INDEX idx_pagamentos_entregadores_entregador ON pagamentos_entregadores USING btree (entregador_id);
CREATE INDEX idx_pagamentos_entregadores_status ON pagamentos_entregadores USING btree (status);
CREATE INDEX idx_pagamentos_entregadores_status_data ON pagamentos_entregadores USING btree (status, data_referencia DESC);
CREATE INDEX idx_pagamentos_online_mercado_pago_payment_id ON pagamentos_online USING btree (mercado_pago_payment_id) WHERE mercado_pago_payment_id IS NOT NULL;
CREATE INDEX idx_pagamentos_online_status ON pagamentos_online USING btree (status);
CREATE INDEX idx_pagamentos_pedido_pedido_id ON pagamentos_pedido USING btree (pedido_id);
CREATE UNIQUE INDEX uq_pagamentos_pedido_pix_online ON pagamentos_pedido USING btree (pedido_id, forma_pagamento) WHERE lower(forma_pagamento::text) = 'pix_online'::text;
CREATE INDEX idx_pedidos_cliente_id ON pedidos USING btree (cliente_id);
CREATE INDEX idx_pedidos_comanda ON pedidos USING btree (comanda);
CREATE INDEX idx_pedidos_created_at ON pedidos USING btree (created_at DESC);
CREATE INDEX idx_pedidos_created_at_id ON pedidos USING btree (created_at DESC, id DESC);
CREATE INDEX idx_pedidos_cupom_codigo ON pedidos USING btree (cupom_codigo);
CREATE INDEX idx_pedidos_cupom_id ON pedidos USING btree (cupom_id);
CREATE INDEX idx_pedidos_garcom_id ON pedidos USING btree (garcom_id) WHERE garcom_id IS NOT NULL;
CREATE INDEX idx_pedidos_mesa_comanda ON pedidos USING btree (mesa, comanda);
CREATE INDEX idx_pedidos_mesa_id ON pedidos USING btree (mesa_id);
CREATE INDEX idx_pedidos_nome_cliente_trgm ON pedidos USING gin (nome_cliente gin_trgm_ops);
CREATE INDEX idx_pedidos_notifier_updated_at ON pedidos USING btree (updated_at DESC, id DESC) WHERE NULLIF(regexp_replace(COALESCE(telefone, ''::character varying)::text, '\D'::text, ''::text, 'g'::text), ''::text) IS NOT NULL AND (lower(COALESCE(status, ''::character varying)::text) = ANY (ARRAY['pendente'::text, 'confirmado'::text, 'confirmada'::text, 'recebido'::text, 'recebida'::text, 'saiu_para_entrega'::text, 'em_rota'::text, 'cancelado'::text, 'cancelada'::text]));
CREATE INDEX idx_pedidos_pagamento_online_flag_status ON pedidos USING btree (pagamento_online, status);
CREATE INDEX idx_pedidos_pagamento_online_status ON pedidos USING btree (pagamento_online_status);
CREATE INDEX idx_pedidos_status ON pedidos USING btree (status);
CREATE INDEX idx_pedidos_status_created_at_id ON pedidos USING btree (status, created_at DESC, id DESC);
CREATE INDEX idx_pedidos_telefone_digits_created_at ON pedidos USING btree (regexp_replace(COALESCE(telefone, ''::character varying)::text, '\D'::text, ''::text, 'g'::text), created_at DESC);
CREATE INDEX idx_pedidos_telefone_trgm ON pedidos USING gin (telefone gin_trgm_ops);
CREATE INDEX idx_pedidos_tipo_created_at_id ON pedidos USING btree (tipo_entrega, created_at DESC, id DESC);
CREATE INDEX idx_produto_adicionais_produto ON produto_adicionais USING btree (produto_id);
CREATE INDEX idx_produtos_categoria ON produtos USING btree (categoria);
CREATE INDEX idx_produtos_disponivel ON produtos USING btree (disponivel);
CREATE INDEX idx_usuarios_cliente_nome ON usuarios_cliente USING btree (nome);
CREATE UNIQUE INDEX idx_usuarios_cliente_telefone ON usuarios_cliente USING btree (telefone);
CREATE INDEX idx_usuarios_cliente_telefone_digits_ultimo_pedido ON usuarios_cliente USING btree (regexp_replace(COALESCE(telefone, ''::text), '\D'::text, ''::text, 'g'::text), ultimo_pedido_em DESC);
CREATE INDEX idx_usuarios_sistema_ativo ON usuarios_sistema USING btree (ativo);
CREATE INDEX idx_usuarios_sistema_nome_usuario ON usuarios_sistema USING btree (nome_usuario);
CREATE INDEX idx_usuarios_sistema_papel ON usuarios_sistema USING btree (papel);


