-- Chaves primárias, unicidades e checks das 44 tabelas do sistema.
-- Fonte: Supabase Management API em 2026-07-28.

set search_path = pg_catalog, public, extensions;

alter table public.adicionais add constraint adicionais_pkey PRIMARY KEY (id);
alter table public.admin_sidebar_config add constraint admin_sidebar_config_pkey PRIMARY KEY (usuario_sistema_id);
alter table public.anotacoes_painel add constraint anotacoes_painel_pkey PRIMARY KEY (id);
alter table public.atividade_garcom add constraint atividade_garcom_pkey PRIMARY KEY (id);
alter table public.atividade_garcom add constraint atividade_garcom_tipo_acao_check CHECK (tipo_acao::text = ANY (ARRAY['pedido_criado'::character varying, 'pedido_modificado'::character varying, 'item_adicionado'::character varying, 'status_alterado'::character varying]::text[]));
alter table public.bairros add constraint bairros_pkey PRIMARY KEY (id);
alter table public.bairros add constraint bairros_nome_key UNIQUE (nome);
alter table public.bebidas add constraint bebidas_pkey PRIMARY KEY (id);
alter table public.caixa_automacao_config add constraint caixa_automacao_config_pkey PRIMARY KEY (id);
alter table public.caixa_automacao_config add constraint caixa_automacao_config_singleton_unique UNIQUE (singleton);
alter table public.caixa_automacao_config add constraint caixa_automacao_config_dias_ativos_validos CHECK (dias_ativos <@ ARRAY[0::smallint, 1::smallint, 2::smallint, 3::smallint, 4::smallint, 5::smallint, 6::smallint]);
alter table public.caixa_automacao_config add constraint caixa_automacao_config_valor_non_negative CHECK (valor_abertura_padrao >= 0::numeric);
alter table public.caixas add constraint caixas_pkey PRIMARY KEY (id);
alter table public.categorias_adicionais add constraint categorias_adicionais_pkey PRIMARY KEY (id);
alter table public.categorias_adicionais add constraint categorias_adicionais_nome_key UNIQUE (nome);
alter table public.categorias_caixa add constraint categorias_caixa_pkey PRIMARY KEY (id);
alter table public.categorias_cardapio add constraint categorias_cardapio_pkey PRIMARY KEY (id);
alter table public.categorias_cardapio add constraint categorias_cardapio_nome_tipo_key UNIQUE (nome, tipo);
alter table public.categorias_cardapio add constraint categorias_cardapio_tipo_check CHECK (tipo = ANY (ARRAY['produto'::text, 'bebida'::text, 'combo'::text]));
alter table public.combo_itens add constraint combo_itens_pkey PRIMARY KEY (id);
alter table public.combos add constraint combos_pkey PRIMARY KEY (id);
alter table public.configuracoes_loja add constraint configuracoes_loja_pkey PRIMARY KEY (id);
alter table public.configuracoes_loja add constraint configuracoes_loja_chave_key UNIQUE (chave);
alter table public.crediario_contas add constraint crediario_contas_pkey PRIMARY KEY (id);
alter table public.crediario_contas add constraint crediario_contas_cliente_chave_key UNIQUE (cliente_chave);
alter table public.crediario_contas add constraint crediario_contas_legado_id_key UNIQUE (legado_id);
alter table public.crediario_contas add constraint crediario_contas_limite_check CHECK (limite_credito IS NULL OR limite_credito >= 0::numeric);
alter table public.crediario_contas add constraint crediario_contas_status_check CHECK (status = ANY (ARRAY['aberto'::text, 'quitado'::text, 'bloqueado'::text, 'arquivado'::text]));
alter table public.crediario_movimentos add constraint crediario_movimentos_pkey PRIMARY KEY (id);
alter table public.crediario_movimentos add constraint crediario_movimentos_legado_id_key UNIQUE (legado_id);
alter table public.crediario_movimentos add constraint crediario_movimentos_status_check CHECK (status = ANY (ARRAY['ativo'::text, 'cancelado'::text]));
alter table public.crediario_movimentos add constraint crediario_movimentos_tipo_check CHECK (tipo = ANY (ARRAY['consumo'::text, 'pagamento'::text, 'ajuste'::text, 'estorno'::text]));
alter table public.crediario_movimentos add constraint crediario_movimentos_valor_check CHECK (valor >= 0::numeric);
alter table public.cupons add constraint cupons_pkey PRIMARY KEY (id);
alter table public.cupons add constraint cupons_aplica_em_ck CHECK (aplica_em::text = ANY (ARRAY['pedido'::character varying::text, 'produto'::character varying::text, 'combo'::character varying::text]));
alter table public.cupons add constraint cupons_aplicacao_relacao_ck CHECK (aplica_em::text = 'pedido'::text AND produto_id IS NULL AND combo_id IS NULL OR aplica_em::text = 'produto'::text AND produto_id IS NOT NULL AND combo_id IS NULL OR aplica_em::text = 'combo'::text AND combo_id IS NOT NULL AND produto_id IS NULL);
alter table public.cupons add constraint cupons_limite_desconto_ck CHECK (limite_desconto IS NULL OR limite_desconto >= 0::numeric);
alter table public.cupons add constraint cupons_pedido_minimo_ck CHECK (pedido_minimo >= 0::numeric);
alter table public.cupons add constraint cupons_tipo_desconto_ck CHECK (tipo_desconto::text = ANY (ARRAY['percentual'::character varying::text, 'valor_fixo'::character varying::text, 'frete_gratis'::character varying::text]));
alter table public.cupons add constraint cupons_total_usos_ck CHECK (total_usos >= 0);
alter table public.cupons add constraint cupons_uso_maximo_por_cliente_ck CHECK (uso_maximo_por_cliente IS NULL OR uso_maximo_por_cliente > 0);
alter table public.cupons add constraint cupons_uso_maximo_total_ck CHECK (uso_maximo_total IS NULL OR uso_maximo_total > 0);
alter table public.cupons add constraint cupons_valor_desconto_ck CHECK (valor_desconto >= 0::numeric);
alter table public.cupons_usos add constraint cupons_usos_pkey PRIMARY KEY (id);
alter table public.cupons_usos add constraint cupons_usos_pedido_unico_ck UNIQUE (pedido_id);
alter table public.entregas add constraint entregas_pkey PRIMARY KEY (id);
alter table public.entregas add constraint entregas_pedido_id_unique UNIQUE (pedido_id);
alter table public.fila_impressao add constraint fila_impressao_pkey PRIMARY KEY (id);
alter table public.fila_impressao add constraint fila_impressao_escopo_ck CHECK (escopo::text = ANY (ARRAY['pedido_completo'::character varying, 'itens_novos'::character varying]::text[]));
alter table public.financas_diarias add constraint financas_diarias_pkey PRIMARY KEY (id);
alter table public.financas_diarias add constraint financas_diarias_nome_pessoa_check CHECK (char_length(TRIM(BOTH FROM nome_pessoa)) > 0);
alter table public.financas_diarias add constraint financas_diarias_valor_check CHECK (valor > 0::numeric);
alter table public.formas_pagamento add constraint formas_pagamento_pkey PRIMARY KEY (id);
alter table public.formas_pagamento add constraint formas_pagamento_codigo_key UNIQUE (codigo);
alter table public.formas_pagamento add constraint formas_pagamento_tipo_taxa_check CHECK (tipo_taxa::text = ANY (ARRAY['nenhuma'::character varying, 'percentual'::character varying, 'fixa'::character varying]::text[]));
alter table public.formas_pagamento add constraint formas_pagamento_valor_taxa_nao_negativo CHECK (valor_taxa >= 0::numeric);
alter table public.funcionarios add constraint funcionarios_pkey PRIMARY KEY (id);
alter table public.historico_caixas add constraint historico_caixas_pkey PRIMARY KEY (id);
alter table public.historico_entregas add constraint historico_entregas_pkey PRIMARY KEY (id);
alter table public.historico_item_adicionais add constraint historico_item_adicionais_pkey PRIMARY KEY (id);
alter table public.historico_itens_pedido add constraint historico_itens_pedido_pkey PRIMARY KEY (id);
alter table public.historico_movimentacoes_caixa add constraint historico_movimentacoes_caixa_pkey PRIMARY KEY (id);
alter table public.historico_pedidos add constraint historico_pedidos_pkey PRIMARY KEY (id);
alter table public.item_adicionais add constraint item_adicionais_pkey PRIMARY KEY (id);
alter table public.itens_pedido add constraint itens_pedido_pkey PRIMARY KEY (id);
alter table public.itens_pedido add constraint itens_pedido_desconto_manual_check CHECK (COALESCE(desconto_manual, 0::numeric) >= 0::numeric);
alter table public.mesas add constraint mesas_pkey PRIMARY KEY (id);
alter table public.mesas add constraint mesas_tipo_check CHECK (tipo::text = ANY (ARRAY['mesa'::character varying, 'comanda'::character varying, 'local_externo'::character varying]::text[]));
alter table public.movimentacoes_caixa add constraint movimentacoes_caixa_pkey PRIMARY KEY (id);
alter table public.notification_preferences add constraint notification_preferences_pkey PRIMARY KEY (id);
alter table public.notification_preferences add constraint notification_preferences_user_id_key UNIQUE (user_id);
alter table public.pagamentos_entregadores add constraint pagamentos_entregadores_pkey PRIMARY KEY (id);
alter table public.pagamentos_entregadores add constraint pagamentos_entregadores_entregador_id_data_referencia_key UNIQUE (entregador_id, data_referencia);
alter table public.pagamentos_entregadores add constraint pagamentos_entregadores_status_check CHECK (status::text = ANY (ARRAY['pendente'::character varying, 'parcial'::character varying, 'pago'::character varying, 'acumulado'::character varying]::text[]));
alter table public.pagamentos_online add constraint pagamentos_online_pkey PRIMARY KEY (id);
alter table public.pagamentos_online add constraint pagamentos_online_external_reference_key UNIQUE (external_reference);
alter table public.pagamentos_online add constraint pagamentos_online_mercado_pago_payment_id_key UNIQUE (mercado_pago_payment_id);
alter table public.pagamentos_online add constraint pagamentos_online_pedido_id_key UNIQUE (pedido_id);
alter table public.pagamentos_online add constraint pagamentos_online_valor_check CHECK (valor >= 0::numeric);
alter table public.pagamentos_pedido add constraint pagamentos_pedido_pkey PRIMARY KEY (id);
alter table public.pedidos add constraint pedidos_pkey PRIMARY KEY (id);
alter table public.pedidos add constraint pedidos_desconto_cupom_nao_negativo CHECK (COALESCE(desconto_cupom, 0::numeric) >= 0::numeric);
alter table public.pedidos add constraint pedidos_desconto_frete_nao_negativo CHECK (COALESCE(desconto_frete, 0::numeric) >= 0::numeric);
alter table public.pedidos add constraint pedidos_desconto_itens_total_check CHECK (COALESCE(desconto_itens_total, 0::numeric) >= 0::numeric);
alter table public.pedidos add constraint pedidos_desconto_manual_check CHECK (COALESCE(desconto_manual, 0::numeric) >= 0::numeric);
alter table public.pedidos add constraint pedidos_mesa_comanda_exclusiva CHECK (NOT (mesa IS NOT NULL AND comanda IS NOT NULL));
alter table public.pedidos add constraint pedidos_pagamento_online_status_check CHECK (pagamento_online_status::text = ANY (ARRAY['nao_aplicavel'::character varying, 'aguardando_pagamento'::character varying, 'pago'::character varying, 'rejeitado'::character varying, 'cancelado'::character varying, 'expirado'::character varying, 'em_analise'::character varying]::text[]));
alter table public.pedidos add constraint pedidos_taxa_pagamento_nao_negativa CHECK (taxa_pagamento >= 0::numeric);
alter table public.pedidos add constraint pedidos_taxa_pagamento_non_negative CHECK (taxa_pagamento >= 0::numeric);
alter table public.pedidos add constraint pedidos_taxa_servico_nao_negativa CHECK (taxa_servico >= 0::numeric);
alter table public.produtividade_config add constraint produtividade_config_pkey PRIMARY KEY (chave);
alter table public.produto_adicionais add constraint produto_adicionais_pkey PRIMARY KEY (id);
alter table public.produto_adicionais add constraint produto_adicionais_produto_id_adicional_id_key UNIQUE (produto_id, adicional_id);
alter table public.produtos add constraint produtos_pkey PRIMARY KEY (id);
alter table public.resumo_anual add constraint resumo_anual_pkey PRIMARY KEY (id);
alter table public.resumo_anual add constraint resumo_anual_ano_key UNIQUE (ano);
alter table public.usuarios_cliente add constraint usuarios_cliente_pkey PRIMARY KEY (id);
alter table public.usuarios_sistema add constraint usuarios_sistema_pkey PRIMARY KEY (id);
alter table public.usuarios_sistema add constraint usuarios_sistema_nome_usuario_key UNIQUE (nome_usuario);
alter table public.usuarios_sistema add constraint usuarios_sistema_papel_check CHECK (papel::text = ANY (ARRAY['admin'::character varying, 'garcom'::character varying, 'entregador'::character varying]::text[]));


