-- Privilégios exatos das 60 funções próprias e comentários do catálogo.
-- Funções exclusivas do serviço WhatsApp e membros de extensions não entram nesta lista.
-- Fonte: Supabase Management API em 2026-07-28.

set search_path = pg_catalog, public, extensions;

revoke all privileges on function
  public.update_updated_at_column(),
  public.atualizar_updated_at_bairros(),
  public.atualizar_updated_at_combos(),
  public.gerar_numero_pedido(),
  public.get_total_pedidos(),
  public.liberar_mesas_expiradas(),
  public.limpar_mesas_expiradas(),
  public.limpar_dados_pedido_excluido(),
  public.update_mesas_updated_at(),
  public.update_notification_preferences_updated_at(),
  public.sync_item_columns(),
  public.preparar_cupom_para_persistencia(),
  public.sincronizar_total_usos_cupom(),
  public.verificar_senha_usuario(p_nome_usuario character varying, p_senha text),
  public.criar_usuario_sistema(p_nome character varying, p_nome_usuario character varying, p_senha text, p_papel character varying, p_avatar_url text, p_cor_avatar character varying, p_funcionario_id uuid),
  public.atualizar_senha_usuario(p_usuario_id uuid, p_nova_senha text),
  public.processar_automacao_caixa(),
  public.sync_pedido_caixa_em_tempo_real(),
  public.touch_usuarios_cliente_updated_at(),
  public.normalizar_telefone_cliente(p_telefone text),
  public.vincular_pedido_usuario_cliente(),
  public.obter_pedidos_cliente_por_telefone(p_telefone text, p_limite integer),
  public.fn_popular_snapshot_fila_impressao(),
  public.buscar_clientes(p_termo text, p_limite integer),
  public.fn_atualizar_snapshot_itens_fila(),
  public.fn_electron_manter_preparando(),
  public.fn_electron_status_preparando(),
  public.fn_fila_impressao_auto(),
  public.fn_fila_impressao_electron_confirmado(),
  public.atualizar_updated_at_categorias_cardapio(),
  public.normalizar_chave_crediario(p_nome text, p_telefone text),
  public.recalcular_crediario_conta(p_conta_id uuid),
  public.atualizar_saldo_crediario_movimento(),
  public.touch_crediario_conta(),
  public.pedido_usa_crediario(p_forma_pagamento text),
  public.sincronizar_pedido_crediario(),
  public.registrar_pagamento_crediario(p_conta_id uuid, p_valor numeric, p_descricao text),
  public.quitar_crediario(p_conta_id uuid, p_descricao text),
  public.snapshot_itens_pedido_crediario(p_pedido_id uuid),
  public.sincronizar_itens_pedido_crediario(),
  public.enviar_pedido_crediario(p_pedido_id uuid),
  public.registrar_pagamento_crediario(p_conta_id uuid, p_valor numeric, p_descricao text, p_metadata jsonb),
  public.cancelar_movimento_crediario(p_movimento_id uuid, p_motivo text),
  public.apagar_item_movimento_crediario(p_movimento_id uuid, p_item_indice integer, p_motivo text),
  public.normalizar_nome_cliente_cadastro(p_nome text),
  public.nome_cliente_cadastro_valido(p_nome text, p_tipo_entrega text),
  public.fila_impressao_automatica_permitida(p_escopo text, p_instante timestamp with time zone),
  public.aplicar_configuracao_automatica_fila_impressao(),
  public.proteger_retorno_fila_impressao_automatica(),
  public.configurar_fila_impressao(p_fila_ativa boolean, p_horario_inicio text, p_horario_fim text, p_imprimir_itens_editados boolean),
  public.estatisticas_pedidos_periodo(p_inicio timestamp with time zone, p_fim timestamp with time zone),
  public.registrar_pagamento_item_crediario(p_movimento_id uuid, p_itens_pagos jsonb, p_forma_pagamento text),
  public.fn_produtividade_nome_generico(p_nome text),
  public.fn_produtividade_pesos(),
  public.fn_produtividade_pedidos_classificados(p_inicio timestamp with time zone, p_fim timestamp with time zone, p_garcom_id uuid),
  public.produtividade_garcons(p_inicio timestamp with time zone, p_fim timestamp with time zone),
  public.produtividade_serie_diaria(p_inicio timestamp with time zone, p_fim timestamp with time zone),
  public.produtividade_ocorrencias(p_inicio timestamp with time zone, p_fim timestamp with time zone, p_garcom_id uuid, p_limite integer, p_offset integer),
  public.produtividade_ler_config(),
  public.produtividade_salvar_config(p_config jsonb)
from public, anon, authenticated, service_role;

grant execute on function
  public.update_updated_at_column(),
  public.atualizar_updated_at_bairros(),
  public.atualizar_updated_at_combos(),
  public.gerar_numero_pedido(),
  public.get_total_pedidos(),
  public.liberar_mesas_expiradas(),
  public.limpar_mesas_expiradas(),
  public.limpar_dados_pedido_excluido(),
  public.update_mesas_updated_at(),
  public.update_notification_preferences_updated_at(),
  public.sync_item_columns(),
  public.preparar_cupom_para_persistencia(),
  public.sincronizar_total_usos_cupom(),
  public.verificar_senha_usuario(p_nome_usuario character varying, p_senha text),
  public.criar_usuario_sistema(p_nome character varying, p_nome_usuario character varying, p_senha text, p_papel character varying, p_avatar_url text, p_cor_avatar character varying, p_funcionario_id uuid),
  public.atualizar_senha_usuario(p_usuario_id uuid, p_nova_senha text),
  public.processar_automacao_caixa(),
  public.sync_pedido_caixa_em_tempo_real(),
  public.touch_usuarios_cliente_updated_at(),
  public.normalizar_telefone_cliente(p_telefone text),
  public.vincular_pedido_usuario_cliente(),
  public.obter_pedidos_cliente_por_telefone(p_telefone text, p_limite integer),
  public.fn_popular_snapshot_fila_impressao(),
  public.buscar_clientes(p_termo text, p_limite integer),
  public.fn_atualizar_snapshot_itens_fila(),
  public.fn_electron_manter_preparando(),
  public.fn_electron_status_preparando(),
  public.fn_fila_impressao_auto(),
  public.fn_fila_impressao_electron_confirmado(),
  public.atualizar_updated_at_categorias_cardapio(),
  public.normalizar_chave_crediario(p_nome text, p_telefone text),
  public.recalcular_crediario_conta(p_conta_id uuid),
  public.atualizar_saldo_crediario_movimento(),
  public.touch_crediario_conta(),
  public.pedido_usa_crediario(p_forma_pagamento text),
  public.sincronizar_pedido_crediario(),
  public.registrar_pagamento_crediario(p_conta_id uuid, p_valor numeric, p_descricao text),
  public.quitar_crediario(p_conta_id uuid, p_descricao text),
  public.snapshot_itens_pedido_crediario(p_pedido_id uuid),
  public.sincronizar_itens_pedido_crediario(),
  public.enviar_pedido_crediario(p_pedido_id uuid),
  public.registrar_pagamento_crediario(p_conta_id uuid, p_valor numeric, p_descricao text, p_metadata jsonb),
  public.cancelar_movimento_crediario(p_movimento_id uuid, p_motivo text),
  public.apagar_item_movimento_crediario(p_movimento_id uuid, p_item_indice integer, p_motivo text),
  public.normalizar_nome_cliente_cadastro(p_nome text),
  public.nome_cliente_cadastro_valido(p_nome text, p_tipo_entrega text),
  public.fila_impressao_automatica_permitida(p_escopo text, p_instante timestamp with time zone),
  public.aplicar_configuracao_automatica_fila_impressao(),
  public.proteger_retorno_fila_impressao_automatica(),
  public.estatisticas_pedidos_periodo(p_inicio timestamp with time zone, p_fim timestamp with time zone),
  public.registrar_pagamento_item_crediario(p_movimento_id uuid, p_itens_pagos jsonb, p_forma_pagamento text)
to public;

grant execute on function
  public.update_updated_at_column(),
  public.atualizar_updated_at_bairros(),
  public.atualizar_updated_at_combos(),
  public.gerar_numero_pedido(),
  public.get_total_pedidos(),
  public.liberar_mesas_expiradas(),
  public.limpar_mesas_expiradas(),
  public.limpar_dados_pedido_excluido(),
  public.update_mesas_updated_at(),
  public.update_notification_preferences_updated_at(),
  public.sync_item_columns(),
  public.preparar_cupom_para_persistencia(),
  public.sincronizar_total_usos_cupom(),
  public.verificar_senha_usuario(p_nome_usuario character varying, p_senha text),
  public.criar_usuario_sistema(p_nome character varying, p_nome_usuario character varying, p_senha text, p_papel character varying, p_avatar_url text, p_cor_avatar character varying, p_funcionario_id uuid),
  public.atualizar_senha_usuario(p_usuario_id uuid, p_nova_senha text),
  public.processar_automacao_caixa(),
  public.sync_pedido_caixa_em_tempo_real(),
  public.touch_usuarios_cliente_updated_at(),
  public.normalizar_telefone_cliente(p_telefone text),
  public.vincular_pedido_usuario_cliente(),
  public.obter_pedidos_cliente_por_telefone(p_telefone text, p_limite integer),
  public.fn_popular_snapshot_fila_impressao(),
  public.buscar_clientes(p_termo text, p_limite integer),
  public.fn_atualizar_snapshot_itens_fila(),
  public.fn_electron_manter_preparando(),
  public.fn_electron_status_preparando(),
  public.fn_fila_impressao_auto(),
  public.fn_fila_impressao_electron_confirmado(),
  public.atualizar_updated_at_categorias_cardapio(),
  public.normalizar_chave_crediario(p_nome text, p_telefone text),
  public.recalcular_crediario_conta(p_conta_id uuid),
  public.atualizar_saldo_crediario_movimento(),
  public.touch_crediario_conta(),
  public.pedido_usa_crediario(p_forma_pagamento text),
  public.sincronizar_pedido_crediario(),
  public.registrar_pagamento_crediario(p_conta_id uuid, p_valor numeric, p_descricao text),
  public.quitar_crediario(p_conta_id uuid, p_descricao text),
  public.snapshot_itens_pedido_crediario(p_pedido_id uuid),
  public.sincronizar_itens_pedido_crediario(),
  public.enviar_pedido_crediario(p_pedido_id uuid),
  public.registrar_pagamento_crediario(p_conta_id uuid, p_valor numeric, p_descricao text, p_metadata jsonb),
  public.cancelar_movimento_crediario(p_movimento_id uuid, p_motivo text),
  public.apagar_item_movimento_crediario(p_movimento_id uuid, p_item_indice integer, p_motivo text),
  public.normalizar_nome_cliente_cadastro(p_nome text),
  public.nome_cliente_cadastro_valido(p_nome text, p_tipo_entrega text),
  public.fila_impressao_automatica_permitida(p_escopo text, p_instante timestamp with time zone),
  public.aplicar_configuracao_automatica_fila_impressao(),
  public.proteger_retorno_fila_impressao_automatica(),
  public.configurar_fila_impressao(p_fila_ativa boolean, p_horario_inicio text, p_horario_fim text, p_imprimir_itens_editados boolean),
  public.estatisticas_pedidos_periodo(p_inicio timestamp with time zone, p_fim timestamp with time zone),
  public.registrar_pagamento_item_crediario(p_movimento_id uuid, p_itens_pagos jsonb, p_forma_pagamento text),
  public.produtividade_garcons(p_inicio timestamp with time zone, p_fim timestamp with time zone),
  public.produtividade_serie_diaria(p_inicio timestamp with time zone, p_fim timestamp with time zone),
  public.produtividade_ocorrencias(p_inicio timestamp with time zone, p_fim timestamp with time zone, p_garcom_id uuid, p_limite integer, p_offset integer),
  public.produtividade_ler_config(),
  public.produtividade_salvar_config(p_config jsonb)
to anon, authenticated;

grant execute on function
  public.update_updated_at_column(),
  public.atualizar_updated_at_bairros(),
  public.atualizar_updated_at_combos(),
  public.gerar_numero_pedido(),
  public.get_total_pedidos(),
  public.liberar_mesas_expiradas(),
  public.limpar_mesas_expiradas(),
  public.limpar_dados_pedido_excluido(),
  public.update_mesas_updated_at(),
  public.update_notification_preferences_updated_at(),
  public.sync_item_columns(),
  public.preparar_cupom_para_persistencia(),
  public.sincronizar_total_usos_cupom(),
  public.verificar_senha_usuario(p_nome_usuario character varying, p_senha text),
  public.criar_usuario_sistema(p_nome character varying, p_nome_usuario character varying, p_senha text, p_papel character varying, p_avatar_url text, p_cor_avatar character varying, p_funcionario_id uuid),
  public.atualizar_senha_usuario(p_usuario_id uuid, p_nova_senha text),
  public.processar_automacao_caixa(),
  public.sync_pedido_caixa_em_tempo_real(),
  public.touch_usuarios_cliente_updated_at(),
  public.normalizar_telefone_cliente(p_telefone text),
  public.vincular_pedido_usuario_cliente(),
  public.obter_pedidos_cliente_por_telefone(p_telefone text, p_limite integer),
  public.fn_popular_snapshot_fila_impressao(),
  public.buscar_clientes(p_termo text, p_limite integer),
  public.fn_atualizar_snapshot_itens_fila(),
  public.fn_electron_manter_preparando(),
  public.fn_electron_status_preparando(),
  public.fn_fila_impressao_auto(),
  public.fn_fila_impressao_electron_confirmado(),
  public.atualizar_updated_at_categorias_cardapio(),
  public.normalizar_chave_crediario(p_nome text, p_telefone text),
  public.recalcular_crediario_conta(p_conta_id uuid),
  public.atualizar_saldo_crediario_movimento(),
  public.touch_crediario_conta(),
  public.pedido_usa_crediario(p_forma_pagamento text),
  public.sincronizar_pedido_crediario(),
  public.registrar_pagamento_crediario(p_conta_id uuid, p_valor numeric, p_descricao text),
  public.quitar_crediario(p_conta_id uuid, p_descricao text),
  public.snapshot_itens_pedido_crediario(p_pedido_id uuid),
  public.sincronizar_itens_pedido_crediario(),
  public.enviar_pedido_crediario(p_pedido_id uuid),
  public.registrar_pagamento_crediario(p_conta_id uuid, p_valor numeric, p_descricao text, p_metadata jsonb),
  public.cancelar_movimento_crediario(p_movimento_id uuid, p_motivo text),
  public.apagar_item_movimento_crediario(p_movimento_id uuid, p_item_indice integer, p_motivo text),
  public.normalizar_nome_cliente_cadastro(p_nome text),
  public.nome_cliente_cadastro_valido(p_nome text, p_tipo_entrega text),
  public.fila_impressao_automatica_permitida(p_escopo text, p_instante timestamp with time zone),
  public.aplicar_configuracao_automatica_fila_impressao(),
  public.proteger_retorno_fila_impressao_automatica(),
  public.configurar_fila_impressao(p_fila_ativa boolean, p_horario_inicio text, p_horario_fim text, p_imprimir_itens_editados boolean),
  public.estatisticas_pedidos_periodo(p_inicio timestamp with time zone, p_fim timestamp with time zone),
  public.registrar_pagamento_item_crediario(p_movimento_id uuid, p_itens_pagos jsonb, p_forma_pagamento text),
  public.fn_produtividade_nome_generico(p_nome text),
  public.fn_produtividade_pesos(),
  public.fn_produtividade_pedidos_classificados(p_inicio timestamp with time zone, p_fim timestamp with time zone, p_garcom_id uuid),
  public.produtividade_garcons(p_inicio timestamp with time zone, p_fim timestamp with time zone),
  public.produtividade_serie_diaria(p_inicio timestamp with time zone, p_fim timestamp with time zone),
  public.produtividade_ocorrencias(p_inicio timestamp with time zone, p_fim timestamp with time zone, p_garcom_id uuid, p_limite integer, p_offset integer),
  public.produtividade_ler_config(),
  public.produtividade_salvar_config(p_config jsonb)
to service_role;

comment on table public.admin_sidebar_config is 'Preferências de sidebar do admin por usuário (ordem e visibilidade dos itens).';
comment on column public.fila_impressao.automatico is 'Distingue eventos automáticos, sujeitos à janela da fila, de impressões manuais.';
comment on column public.pagamentos_pedido.itens_pagos is 'Itens cobertos por este pagamento (jsonb array). Formato igual ao snapshot_itens_pedido_crediario.';
comment on table public.produtividade_config is 'Pesos de pontuação e metas do módulo de produtividade dos garçons. Penalidades são positivas e subtraídas no cálculo.';
comment on function public.estatisticas_pedidos_periodo(p_inicio timestamp with time zone, p_fim timestamp with time zone) is 'Agrega count e sum(total) de pedidos no periodo, excluindo cancelado e aguardando_pagamento. Usado pelo dashboard admin para evitar paginar todas as linhas.';
comment on function public.fn_produtividade_nome_generico(p_nome text) is 'true quando o nome do cliente não identifica ninguém (vazio, "cliente", "mesa 7", só dígitos, 2 letras…).';
comment on function public.fn_produtividade_pesos() is 'Pesos e metas do módulo de produtividade, com os defaults do código aplicados sobre a tabela de config.';
comment on function public.fn_produtividade_pedidos_classificados(p_inicio timestamp with time zone, p_fim timestamp with time zone, p_garcom_id uuid) is 'Pedidos de garçom no período com as regras de boa prática já avaliadas. Fonte única usada pelas demais funções.';
comment on function public.produtividade_garcons(p_inicio timestamp with time zone, p_fim timestamp with time zone) is 'Métricas e pontuação de cada garçom no período. Pedidos de qualquer status entram; cancelado não pontua criação.';
comment on function public.produtividade_serie_diaria(p_inicio timestamp with time zone, p_fim timestamp with time zone) is 'Pontos e pedidos por dia operacional (corte 03:00 America/Sao_Paulo) e por garçom.';
comment on function public.produtividade_ocorrencias(p_inicio timestamp with time zone, p_fim timestamp with time zone, p_garcom_id uuid, p_limite integer, p_offset integer) is 'Pedidos que perderam pontos no período, com os motivos e o total descontado. Paginada; total_registros repete a contagem completa.';
comment on function public.produtividade_ler_config() is 'Pesos e metas vigentes. A tabela produtividade_config não é acessível diretamente pelo anon.';
comment on function public.produtividade_salvar_config(p_config jsonb) is 'Grava apenas as chaves conhecidas, com valor entre 0 e 100000. Retorna a configuração completa.';

